# Obtener todos los usuarios
GET http://localhost:3000/usuarios

###

# Obtener un usuario por nombre
GET http://localhost:3000/usuarios/nombreusuario

###

# Agregar un nuevo usuario
POST http://localhost:3000/usuarios
Content-Type: application/json

{
    "nombre": "Reyes",
    "edad": 31,
    "lugarProcedencia": "Estados Unidos"
}

###

# Actualizar un usuario existente
PUT http://localhost:3000/usuarios/Ryu
Content-Type: application/json

{
    "nombre": "",
    "edad": 46,
    "lugarProcedencia": ""
}

###

# Eliminar un usuario
DELETE http://localhost:3000/usuarios/Ryu